import test from 'node:test';
import assert from 'node:assert/strict';
import {planSupplierInput,planSupplierDropdowns,planPolicySplit,planLayoutReorder,splitPolicyValue,planPolicyImport,buildPolicyArchive,compareSharedToLegacy,inputSpec} from '../scripts/supplier-input-sheet.mjs';
const now=Date.parse('2026-10-03T12:00:00Z');
const legacy=inputSpec.legacyLayouts['2026-10-02'];
const sheet=(id,title,headers,grid={frozenRowCount:1,frozenColumnCount:0})=>({properties:{sheetId:id,title,gridProperties:{rowCount:1000,columnCount:headers.length,...grid}},data:[{rowData:[{values:headers.map(h=>({userEnteredValue:{stringValue:h}}))}]}]});
const shared=inputSpec.supplierChannels.sharedInputSheet;
const fixture=()=>({capturedAt:new Date(now).toISOString(),binding:{spreadsheetId:'test',summarySheetId:1,guideSheetId:2,suppliers:shared.map((r,i)=>({sheetId:3+i,title:r.tab,code:r.code}))},sheetInventory:[1,2,...shared.map((_,i)=>3+i)].map(sheetId=>({sheetId})),spreadsheet:{spreadsheetId:'test',sheets:[sheet(1,'종합',inputSpec.summaryHeaders),sheet(2,'관리안내',['안내']),...shared.map((r,i)=>sheet(3+i,r.tab,inputSpec.inputHeaders))]}});
const policyFixture=()=>{const f=fixture(),d=sheet(3,'웰릭스',legacy.inputHeaders);const h=legacy.inputHeaders,values=h.map(()=>({}));values[h.indexOf('차량번호')]={userEnteredValue:{stringValue:'TEST-1'}};values[h.indexOf('정책코드')]={userEnteredValue:{stringValue:'POL-01'}};d.data[0].rowData.push({values});return {runId:'test-run',capturedAt:f.capturedAt,suppliers:[{sheetId:3,sourceId:'source',sourceTab:'policy'}],destinations:[d],captures:[{sourceId:'source',sourceTab:'policy',complete:true,rows:[{values:['정책코드','추가주행 금액','정비'].map(stringValue=>({userEnteredValue:{stringValue}}))},{values:['POL-01','대여료의 10%','연2회오일'].map(stringValue=>({userEnteredValue:{stringValue}}))}]}]};};

test('2026-10-03-order layout: 33 vehicle/rate columns in the 대표 order then 41 one-fact policy columns',()=>{
  assert.equal(inputSpec.layoutVersion,'2026-10-03-order');
  assert.equal(inputSpec.vehicleHeaders.length,33);assert.equal(inputSpec.policyHeaders.length,41);
  const v=inputSpec.vehicleHeaders,before=(a,b)=>assert.ok(v.indexOf(a)<v.indexOf(b),a+'<'+b);
  assert.deepEqual(v.slice(0,9),['회사명','차량상태','배차상태','상품구분','차량번호','제조사','모델','세부모델','세부트림']);
  for(const h of ['외부색상','내부색상','최초등록일','입고일자','사진링크','기타기간①','기타기간②','기타기간③'])before('세부트림',h),before(h,'연식');
  before('연식','주행거리');before('주행거리','배기량');before('배기량','연료');before('연료','단기보증');before('60개월','차명 원문');assert.deepEqual(v.slice(-3),['차명 원문','옵션 원문','차량가격']);
  assert.equal(inputSpec.policyHeaders[0],'예외사항');assert.ok(inputSpec.dropdowns['모델']?.includes('그랜저'));assert.ok(!inputSpec.dropdowns['세부모델']);
  assert.equal(inputSpec.legacyLayouts['2026-10-03-split'].inputHeaders.length,71);
  for(const h of inputSpec.policyHeaders)assert.ok(!h.includes('/')||h==='선불/후불',h);
  assert.equal(inputSpec.legacyLayouts['2026-10-03'].inputHeaders.length,62);
  assert.deepEqual(inputSpec.inputHeaders,[...inputSpec.vehicleHeaders,...inputSpec.policyHeaders]);
  assert.deepEqual(inputSpec.summaryHeaders,inputSpec.inputHeaders);
  assert.equal(new Set(inputSpec.inputHeaders).size,74);
  
  assert.equal(inputSpec.vehicleHeaders.at(-1),'차량가격');
  assert.deepEqual(inputSpec.policyHeaders.slice(0,8),['예외사항','심사','보험료','기본연령','면허기간','연주행','1만km+','21세+']);
  assert.equal(inputSpec.policyHeaders.at(-1),'비고');assert.ok(inputSpec.policyHeaders.includes('계좌번호'));
  for(const gone of ['정책코드','점검사항','차종코드','차명(정제)','제조사(정제)','26세+'])assert.ok(!inputSpec.inputHeaders.includes(gone),gone);
  assert.equal(inputSpec.frozenRowCount,1);assert.equal(inputSpec.frozenColumnCount,0);assert.equal(inputSpec.font.italic,false);
  assert.ok(!inputSpec.numberHeaders.includes('연식'));
});
test('matching sheet verifies with zero write requests and leaves input untouched',()=>{const f=fixture(),before=JSON.stringify(f),r=planSupplierInput(f,inputSpec,now);assert.equal(JSON.stringify(f),before);assert.equal(r.status,'LAYOUT_VERIFIED');assert.deepEqual(r.requests,[]);assert.match(r.scope,/VERIFY_ONLY/);});
test('any header difference is LAYOUT_MISMATCH HOLD — old 2026-10-02 layout, reorder, missing, extra',()=>{
  const cases=[f=>{f.spreadsheet.sheets[2]=sheet(3,'웰릭스',legacy.inputHeaders);},f=>{f.spreadsheet.sheets[0]=sheet(1,'종합',legacy.summaryHeaders);},f=>{f.spreadsheet.sheets[2].data[0].rowData[0].values.reverse();},f=>{f.spreadsheet.sheets[2].data[0].rowData[0].values.pop();},f=>{f.spreadsheet.sheets[2].data[0].rowData[0].values.push({userEnteredValue:{stringValue:'정책코드'}});},f=>{f.spreadsheet.sheets[2].data[0].rowData[0].values[0].userEnteredValue.stringValue='';}];
  for(const mutate of cases){const f=fixture();mutate(f);assert.throws(()=>planSupplierInput(f,inputSpec,now),e=>/HOLD: LAYOUT_MISMATCH/.test(e.message)&&e.mismatched.length===1);}
});
test('extra trailing header cells and hidden bound tabs are HOLD; hidden unbound archive tabs are ignored',()=>{const a=fixture();a.spreadsheet.sheets[2].data[0].rowData[0].values.push({});assert.throws(()=>planSupplierInput(a,inputSpec,now),/LAYOUT_MISMATCH/);for(const id of [0,2]){const f=fixture();f.spreadsheet.sheets[id].properties.hidden=true;assert.throws(()=>planSupplierInput(f,inputSpec,now),e=>/LAYOUT_MISMATCH/.test(e.message)&&e.mismatched[0].hidden===true);}const f=fixture();f.spreadsheet.sheets.push({...sheet(9000,'정책원문',['runId']),properties:{sheetId:9000,title:'정책원문',hidden:true,gridProperties:{rowCount:10,columnCount:1}}});f.sheetInventory.push({sheetId:9000});assert.equal(planSupplierInput(f,inputSpec,now).status,'LAYOUT_VERIFIED');});
test('frozen rows/columns drift is reported, never written',()=>{const f=fixture();f.spreadsheet.sheets[2].properties.gridProperties.frozenColumnCount=2;const r=planSupplierInput(f,inputSpec,now);assert.equal(r.status,'LAYOUT_VERIFIED_WITH_PRESENTATION_DRIFT');assert.deepEqual(r.drift.map(d=>[d.sheetId,d.frozenColumnCount]),[[3,2]]);assert.deepEqual(r.requests,[]);});
test('fail closed binding freshness inventory duplicate and production workbook',()=>{for(const mutate of [f=>f.binding.spreadsheetId='other',f=>f.capturedAt='2026-09-01',f=>f.sheetInventory.pop(),f=>f.binding.suppliers.push({...f.binding.suppliers[0]}),f=>{f.spreadsheet.sheets.push(sheet(9001,'숨김아님',['x']));f.sheetInventory.push({sheetId:9001});}]){const f=fixture();mutate(f);assert.throws(()=>planSupplierInput(f,inputSpec,now),/HOLD/);}});
test('channel split: 19 shared-sheet suppliers, 5 direct/own-sheet suppliers, no overlap; binding must match exactly',()=>{const c=inputSpec.supplierChannels,codes=c.sharedInputSheet.map(r=>r.code),outside=c.notInSharedSheet.map(r=>r.code);assert.equal(codes.length,19);assert.equal(new Set(codes).size,19);assert.equal(new Set(c.sharedInputSheet.map(r=>r.tab)).size,19);assert.deepEqual(outside.sort(),['RP004','RP006','RP012','RP023','RP031']);assert.ok(outside.every(o=>!codes.includes(o)));assert.ok(codes.includes('RP013'));assert.match(c.membershipRule,/아이카/);assert.throws(()=>compareSharedToLegacy({...compareFixture(),binding:{suppliers:[{title:'아이카',code:'RP004'}]}},inputSpec,now),/excluded from the shared sheet/);
  for(const mutate of [f=>{f.binding.suppliers[0].code='RP031';},f=>{f.binding.suppliers[0].title='이안카';},f=>{f.binding.suppliers[0].code='RP020';f.binding.suppliers[1].code='RP013';},f=>{f.binding.suppliers.pop();f.spreadsheet.sheets.pop();f.sheetInventory.pop();},f=>{f.spreadsheet.sheets[2].properties.title='이안카';},f=>{f.binding.suppliers[0]={...f.binding.suppliers[0],title:'아이카',code:'RP004'};f.spreadsheet.sheets[2].properties.title='아이카';}]){const f=fixture();mutate(f);assert.throws(()=>planSupplierInput(f,inputSpec,now),/HOLD/);}
  const r=compareSharedToLegacy(compareFixture(),inputSpec,now);assert.equal(r.notCompared.length,18);});
test('planner refuses a spec that is not verify-only',()=>{assert.throws(()=>planSupplierInput(fixture(),{...inputSpec,plannerMode:'WRITE'},now),/VERIFY_ONLY/);});
test('manual authority is explicit and automatic source refresh stays disabled',()=>{assert.equal(inputSpec.managementMode,'MANUAL_DIRECT_GOOGLE_SHEETS');assert.equal(inputSpec.manualAuthority,'VISIBLE_SUPPLIER_TABS');assert.equal(inputSpec.automaticSourceRefresh,false);});
test('policy import refuses the current layout because it has no 정책코드',()=>{const f=policyFixture();f.destinations=[sheet(3,'웰릭스',inputSpec.inputHeaders)];assert.throws(()=>planPolicyImport(f,now),/2026-10-02 layout only/);});
test('compact policy retains money units, zero, one-sided bounds and repair percent basis',()=>{for(const [low,high,expected]of [['50만원','100만원','50~100만원'],['50만원','50만원','50만원'],['50만원','','최소 50만원'],['','100만원','최대 100만원'],['50만원','1억원','50만원~1억원'],[0,0,'0']]){const f=policyFixture(),src=f.captures[0].rows;const names=['대인보상한도','대인면책금','자차보상한도','자차수리비율','자차최소면책금','자차최대면책금'];src[0].values.push(...names.map(stringValue=>({userEnteredValue:{stringValue}})));src[1].values.push(...['무한',0,'차량가액','20%',low,high].map(v=>({userEnteredValue:typeof v==='number'?{numberValue:v}:{stringValue:v}})));const p=planPolicyImport(f,now);assert.equal(p.writes.find(w=>w.header==='대인').value.stringValue,'무한 / 0');const car=p.writes.find(w=>w.header==='자차');assert.equal(car.value.stringValue,'차량가액 / 수리비 20% / '+expected);assert.match(car.fullDescription,/자차수리비율: 20%/);}});
test('compact rewrite requires exact import ownership and old presentation; repeat is idempotent',()=>{for(const variant of ['owned','edited','unowned']){const f=policyFixture(),src=f.captures[0].rows;src[0].values.push(...['대인보상한도','대인면책금'].map(stringValue=>({userEnteredValue:{stringValue}})));src[1].values.push(...['무한','50만원'].map(stringValue=>({userEnteredValue:{stringValue}})));const ci=legacy.inputHeaders.indexOf('대인'),cells=f.destinations[0].data[0].rowData[1].values;cells[ci]={userEnteredValue:{stringValue:'대인보상한도: 무한\n대인면책금: '+(variant==='edited'?'60만원':'50만원')},note:'원문 정책 이관 / '+(variant==='unowned'?'other':'original')+' / policy 2행 / POL-01 / 원천 단위 그대로'};f.rewriteImportedPolicyPresentation={runId:'original'};const p=planPolicyImport(f,now),w=p.writes.find(w=>w.header==='대인');if(variant==='owned'){assert.equal(w.value.stringValue,'무한 / 50만원');assert.ok(w.previous.note.includes('original'));for(const write of p.writes)cells[write.column]={userEnteredValue:write.value,note:write.previous?.note??'import'};assert.equal(planPolicyImport(f,now).writes.length,0);}else{assert.equal(w,undefined);assert.ok(p.holds.some(h=>h.reason==='POLICY_PRESENTATION_NOT_OWNED_OR_CHANGED'));}}});
test('policy exact binding, zero/formula preservation and original rate text',()=>{const f=policyFixture(),col=legacy.inputHeaders.indexOf('정비');f.destinations[0].data[0].rowData[1].values[col]={userEnteredValue:{formulaValue:'=""'},effectiveValue:{stringValue:''}};const p=planPolicyImport(f,now);assert.equal(p.writes.length,1);assert.equal(p.writes[0].value.stringValue,'대여료의 10%');assert.equal(p.writes[0].source.runId,'test-run');assert.equal(p.outcomes[0].status,'MATCHED');});
test('unreadable source fails; blank/ambiguous/numeric codes hold without generic fallback',()=>{const broken=policyFixture();broken.captures[0].complete=false;assert.throws(()=>planPolicyImport(broken,now),/HOLD/);for(const kind of ['blank','duplicate','numeric']){const f=policyFixture();if(kind==='duplicate')f.captures[0].rows.push(f.captures[0].rows[1]);else f.destinations[0].data[0].rowData[1].values[legacy.inputHeaders.indexOf('정책코드')]={userEnteredValue:kind==='numeric'?{numberValue:12}:{stringValue:''}};const p=planPolicyImport(f,now);assert.equal(p.writes.length,0);assert.equal(p.holds.length,1);assert.equal(p.outcomes.length,1);}});
test('archive aligns by label when source schemas differ; records schema hash and raw formula',()=>{const f=policyFixture(),other={sourceId:'second',sourceTab:'policy',complete:true,rows:[{values:['정비','정책코드'].map(stringValue=>({userEnteredValue:{stringValue}}))},{values:[{userEnteredValue:{formulaValue:'="미제공"'},effectiveValue:{stringValue:'미제공'}},{userEnteredValue:{stringValue:'POL-02'}}]}]};const a=buildPolicyArchive([...f.captures,other],'run',f.capturedAt);assert.equal(a.rows[2].values[a.headers.indexOf('정책코드')].userEnteredValue.stringValue,'POL-02');assert.equal(a.rows[2].values[a.headers.indexOf('정비')].note,'원천 수식: ="미제공"');assert.notEqual(a.rows[1].values[5].userEnteredValue.stringValue,a.rows[2].values[5].userEnteredValue.stringValue);});
test('source 0.2 displays 20 percent without changing raw numeric value or losing unit note',()=>{const f=policyFixture();f.captures[0].rows[0].values.push({userEnteredValue:{stringValue:'자차수리비율'}});f.captures[0].rows[1].values.push({userEnteredValue:{numberValue:0.2},effectiveValue:{numberValue:0.2},formattedValue:'20%',userEnteredFormat:{numberFormat:{type:'PERCENT',pattern:'0%'}},note:'수리비의 비율'});const p=planPolicyImport(f,now);assert.equal(p.writes.find(w=>w.header==='자차').value.stringValue,'수리비 20%');const a=buildPolicyArchive(f.captures,'run',f.capturedAt),c=a.rows[1].values[a.headers.indexOf('자차수리비율')];assert.equal(c.userEnteredValue.numberValue,0.2);assert.equal(c.userEnteredFormat.numberFormat.type,'PERCENT');assert.equal(c.note,'수리비의 비율');});
const cmp=inputSpec.legacyCompare;
const sharedRow=o=>inputSpec.inputHeaders.map(h=>o[h]??'');
const legacyHeaders=['차량번호','상태','분류','모델명','차명(세부모델+트림)','1개월','12개월','차량가격','정책코드'];
const legacyRow=o=>legacyHeaders.map(h=>o[h]??'');
const compareFixture=()=>({binding:{suppliers:[{title:'웰릭스',code:'RP013'}]},
  shared:{capturedAt:new Date(now).toISOString(),tabs:[{title:'웰릭스',headers:[...inputSpec.inputHeaders],rows:[sharedRow({'회사명':'예시','차량번호':'12가 3456','차량상태':'출고가능','1개월':900000,'차량가격':30000000,'예외사항':'정책은 비교 안 함'}),sharedRow({'차량번호':'99하9999','차량상태':'계약중'}),[]]}]},
  legacy:[{code:'RP013',tab:'재고',complete:true,capturedAt:new Date(now).toISOString(),headers:legacyHeaders,rows:[legacyRow({'차량번호':'12가3456','상태':'출고가능','1개월':'900,000','차량가격':30000000,'정책코드':'P1'}),legacyRow({'차량번호':'99하9999','상태':'출고가능'})]}]});
test('compare is read-only and maps renamed columns; spaces in plates and number formatting are not differences',()=>{const f=compareFixture(),before=JSON.stringify(f),r=compareSharedToLegacy(f,inputSpec,now);assert.equal(JSON.stringify(f),before);assert.ok(!('requests' in r));assert.match(r.scope,/COMPARE_ONLY/);const t=r.results[0];assert.equal(t.counts.matched,1);assert.deepEqual(t.different,[{plate:'99하9999',fields:['차량상태']}]);assert.equal(t.status,'DIFFERENT');assert.equal(r.status,'NOT_IN_SYNC');assert.equal(cmp.fieldMap['차량상태'],'상태');assert.ok(!('회사명' in cmp.fieldMap));for(const h of inputSpec.policyHeaders)assert.ok(!(h in cmp.fieldMap));});
const fullLegacy=f=>{const map=cmp.fieldMap,hs=[...new Set(Object.values(map))];const l=f.legacy[0],rows=l.rows.map(r=>hs.map(h=>{const i=l.headers.indexOf(h);return i<0?'':r[i];}));l.headers=hs;l.rows=rows;return f;};
test('compare reports one-sided plates, duplicates and rows without plate; identical sides are IN_SYNC',()=>{const f=compareFixture();f.legacy[0].rows[1]=legacyRow({'차량번호':'99하9999','상태':'계약중'});assert.equal(compareSharedToLegacy(f,inputSpec,now).status,'NOT_IN_SYNC','missing legacy columns are never IN_SYNC');fullLegacy(f);assert.equal(compareSharedToLegacy(f,inputSpec,now).status,'ALL_IN_SYNC');f.shared.tabs[0].rows.push(sharedRow({'차량번호':'11나1111'}),sharedRow({'차량상태':'출고가능'}));const lrow=o=>f.legacy[0].headers.map(h=>o[h]??'');f.legacy[0].rows.push(lrow({'차량번호':'22다2222'}),lrow({'차량번호':'12가3456'}));const t=compareSharedToLegacy(f,inputSpec,now).results[0];assert.deepEqual(t.onlyShared,['11나1111']);assert.deepEqual(t.onlyLegacy,['22다2222']);assert.deepEqual(t.duplicates,[{plate:'12가3456',shared:1,legacy:2}]);assert.equal(t.counts.sharedRowsWithoutPlate,1);assert.equal(t.counts.matched,1);assert.deepEqual(t.notInLegacy,[]);assert.equal(t.counts.comparedFields,Object.keys(cmp.fieldMap).length-1);});
test('compare does not equate two differently written numeric strings or text with numbers',()=>{const f=compareFixture();f.legacy[0].rows[0][legacyHeaders.indexOf('1개월')]='90만원';assert.deepEqual(compareSharedToLegacy(f,inputSpec,now).results[0].different.find(d=>d.plate==='12가3456').fields,['1개월']);});
test('compare fails closed: stale capture, wrong shared layout, missing shared tab; unreadable legacy is reported not zero',()=>{for(const mutate of [f=>f.shared.capturedAt='2026-10-03T10:00:00Z',f=>f.legacy[0].capturedAt='2026-10-01T00:00:00Z',f=>f.shared.tabs[0].headers.pop(),f=>f.shared.tabs=[],f=>f.binding.suppliers.push({title:'웰릭스',code:'X'})]){const f=compareFixture();mutate(f);assert.throws(()=>compareSharedToLegacy(f,inputSpec,now),/HOLD/);}
  for(const [mutate,status] of [[f=>f.legacy=[],'LEGACY_NOT_CAPTURED'],[f=>f.legacy[0].complete=false,'LEGACY_UNREADABLE'],[f=>f.legacy[0].tab='운영정책','LEGACY_UNREADABLE'],[f=>{f.legacy[0].headers=f.legacy[0].headers.map(h=>h==='차량번호'?'번호':h);},'LEGACY_UNREADABLE']]){const f=compareFixture();mutate(f);const r=compareSharedToLegacy(f,inputSpec,now);assert.equal(r.results[0].status,status);assert.equal(r.status,'NOT_IN_SYNC');}});
test('compare: plate-only legacy, duplicate legacy headers, duplicate or unbound legacy captures',()=>{const a=compareFixture();a.legacy[0].headers=['차량번호'];a.legacy[0].rows=[['12가3456'],['99하9999']];const r=compareSharedToLegacy(a,inputSpec,now).results[0];assert.equal(r.status,'DIFFERENT');assert.equal(r.counts.comparedFields,0);
  const b=compareFixture();b.legacy[0].headers=[...legacyHeaders.slice(0,-1),'1개월'];assert.equal(compareSharedToLegacy(b,inputSpec,now).results[0].reason,'duplicate legacy headers');
  const c=compareFixture();c.legacy.push({...c.legacy[0]});assert.throws(()=>compareSharedToLegacy(c,inputSpec,now),/One legacy capture/);
  const d=fullLegacy(compareFixture());d.legacy[0].rows[1][d.legacy[0].headers.indexOf('상태')]='계약중';d.legacy.push({...d.legacy[0],code:'OTHER'});const e=compareSharedToLegacy(d,inputSpec,now);assert.deepEqual(e.unboundLegacy,['OTHER']);assert.equal(e.results[0].status,'IN_SYNC');assert.equal(e.status,'NOT_IN_SYNC');});
test('dropdown setup: validation-only requests on supplier tabs, every column decided, summary untouched',()=>{const f=fixture(),before=JSON.stringify(f),p=planSupplierDropdowns(f,inputSpec,now);assert.equal(JSON.stringify(f),before);assert.equal(p.scope,'SUPPLIER_TAB_DATA_VALIDATION_ONLY');assert.ok(p.requests.every(r=>Object.keys(r).join()==='setDataValidation'&&r.setDataValidation.rule));assert.equal(p.requests.length,19*Object.keys(inputSpec.dropdowns).length);assert.ok(!p.requests.some(r=>r.setDataValidation.range.sheetId===1||r.setDataValidation.range.sheetId===2));assert.ok(p.requests.every(r=>r.setDataValidation.range.startRowIndex===1));
  const col=h=>inputSpec.inputHeaders.indexOf(h),at=(h,id=3)=>p.requests.find(r=>r.setDataValidation.range.sheetId===id&&r.setDataValidation.range.startColumnIndex===col(h))?.setDataValidation;
  assert.deepEqual(at('보험료').rule.condition.values.map(v=>v.userEnteredValue),['포함','불포함']);assert.equal(at('보험료').rule.strict,false);assert.equal(at('비고'),undefined,'free text untouched');assert.equal(at('계좌번호'),undefined);assert.deepEqual(at('대물면책').rule.condition.values.map(v=>v.userEnteredValue),['없음','30만원','50만원','100만원','협의']);assert.ok(at('21세+').rule.condition.values.some(v=>v.userEnteredValue==='대여료의 10%'));
  for(const h of inputSpec.inputHeaders)assert.ok(Boolean(inputSpec.dropdowns[h])!==inputSpec.dropdownPolicy.freeText.includes(h),h);
  for(const h of inputSpec.policyHeaders)if(inputSpec.dropdowns[h])assert.equal(inputSpec.dropdowns[h].includes('협의'),!inputSpec.dropdownPolicy.negotiableExceptions.includes(h),'협의 rule for '+h);
  for(const r of ['50~100만원','100~200만원','200~400만원','300~400만원','300~500만원'])assert.ok(inputSpec.dropdowns['자차면책'].includes(r),r);
  for(const [h,vals] of Object.entries(inputSpec.dropdownPolicy.existingValuesNotInList))for(const [v] of vals)assert.ok(!inputSpec.dropdowns[h].includes(v),h+v);
  const g=fixture();g.spreadsheet.sheets[2].data[0].rowData[0].values.reverse();assert.throws(()=>planSupplierDropdowns(g,inputSpec,now),/LAYOUT_MISMATCH/);
  assert.throws(()=>planSupplierDropdowns(fixture(),{...inputSpec,dropdowns:{...inputSpec.dropdowns,'보험료':undefined}},now),/dropdown or a free-text/);});
const old=inputSpec.legacyLayouts['2026-10-03'].inputHeaders,splitH=inputSpec.legacyLayouts['2026-10-03-split'].inputHeaders;
const splitFixture=(cells={})=>{const f=fixture();f.spreadsheet.sheets=f.spreadsheet.sheets.map(sh=>{const id=sh.properties.sheetId;if(id===2)return sh;const t=sheet(id,sh.properties.title,old);t.properties.gridProperties={...t.properties.gridProperties,rowCount:id===1?1000:3,columnCount:62};if(id!==1){const row=o=>({values:old.map(h=>o[h]===undefined?{}:{userEnteredValue:{stringValue:o[h]}})});t.data[0].rowData.push(row(id===3?cells:{'대인/면책':'무한 / 50만원'}),row({}));}return t;});return f;};
test('policy split: every observed value shape splits into one fact per cell',()=>{const cases=[['대인/면책','무한 / 50만원',['무한','50만원']],['대물/면책','10억원',['10억원','']],['자차/면책','차량가액 / 수리비 20% / 50~100만원',['차량가액','20%','50~100만원']],['자차/면책','차량가액 / 50~100만원',['차량가액','','50~100만원']],['자차/면책','50~100만원',['','','50~100만원']],['자손/면책','1천5백만원 / 30만원',['1천5백만원','30만원']],['무보험/면책','없음',['없음','']],['무보험/면책','없음 / 없음',['없음','없음']],['운전자범위','개인 계약자 본인 / 법인 대표자 본인',['계약자 본인','대표자 본인']],['추가운전','2인까지 / 무료',['2인까지','무료']],['승계','협의 / 100만원',['협의','100만원']],['승계','',['','']]];for(const [h,v,want] of cases)assert.deepEqual(splitPolicyValue(h,v),want,h+v);
  for(const [h,v] of [['대인/면책','무한'],['대인/면책','무한 / 50만원 / 기타'],['자차/면책','수리비 20% / 50만원'],['자차/면책','차량가액'],['운전자범위','본인 / 임직원'],['추가운전','1인까지'],['대물/면책','1억원 /  / 50만원']])assert.throws(()=>splitPolicyValue(h,v),/HOLD/,h+v);});
test('policy split plan: inserts columns right-to-left, rewrites headers and split cells only, regenerates summary; any unparsed cell holds everything',()=>{
  const f=splitFixture({'자차/면책':'차량가액 / 수리비 20% / 50~100만원','운전자범위':'개인 본인 / 법인 임직원','보험료':'포함'}),before=JSON.stringify(f),p=planPolicySplit(f,inputSpec,now);assert.equal(JSON.stringify(f),before);
  const ins=p.requests.filter(r=>r.insertDimension&&r.insertDimension.range.sheetId===3).map(r=>r.insertDimension.range.startIndex);assert.deepEqual(ins,[...ins].sort((a,b)=>b-a));assert.equal(ins.length,8);
  const added=p.requests.filter(r=>r.insertDimension&&r.insertDimension.range.sheetId===3).reduce((n,r)=>n+r.insertDimension.range.endIndex-r.insertDimension.range.startIndex,0);assert.equal(added,9);
  assert.ok(p.requests.every(r=>['insertDimension','updateCells','updateDimensionProperties','setDataValidation'].includes(Object.keys(r)[0])));
  const dv=p.requests.filter(r=>r.setDataValidation&&r.setDataValidation.range.sheetId===3);assert.equal(dv.length,17);for(const r of dv){const h=splitH[r.setDataValidation.range.startColumnIndex];assert.deepEqual(r.setDataValidation.rule.condition.values.map(v=>v.userEnteredValue),inputSpec.dropdowns[h],h);}
  assert.ok(p.requests.findIndex(r=>r.setDataValidation)>p.requests.findLastIndex(r=>r.insertDimension&&r.insertDimension.range.sheetId===3),'validation after inserts');
  const cellAt=(h,id=3)=>p.requests.find(r=>r.updateCells&&r.updateCells.start.sheetId===id&&r.updateCells.start.rowIndex===1&&r.updateCells.start.columnIndex===splitH.indexOf(h))?.updateCells.rows[0].values[0].userEnteredValue?.stringValue;
  assert.equal(cellAt('자차한도'),'차량가액');assert.equal(cellAt('자차수리비'),'20%');assert.equal(cellAt('자차면책'),'50~100만원');assert.equal(cellAt('개인운전자'),'본인');assert.equal(cellAt('법인운전자'),'임직원');assert.equal(cellAt('보험료'),undefined,'unsplit columns are not rewritten');
  const written=p.requests.filter(r=>r.updateCells&&r.updateCells.start.sheetId===3&&r.updateCells.start.rowIndex===1);assert.ok(written.every(r=>r.updateCells.rows.length===1),'only up to the last non-empty row');
  assert.ok(!p.requests.some(r=>r.updateCells&&r.updateCells.start.sheetId===3&&r.updateCells.start.rowIndex===1&&r.updateCells.start.columnIndex===splitH.indexOf('대인한도')),'empty source column writes nothing');
  const head=p.requests.find(r=>r.updateCells&&r.updateCells.start.sheetId===3&&r.updateCells.start.rowIndex===0).updateCells.rows[0].values.map(v=>v.userEnteredValue.stringValue);assert.deepEqual(head,splitH);
  const sum=p.requests.filter(r=>r.updateCells?.start.sheetId===1)[0].updateCells;assert.equal(sum.rows[0].values.length,71);assert.match(sum.rows[1].values[0].userEnteredValue.formulaValue,/'웰릭스'!A2:BS3/);assert.equal(p.requests.find(r=>r.insertDimension?.range.sheetId===1).insertDimension.range.endIndex,71);
  const offList=splitFixture({'대인/면책':'무한 / 70만원'});assert.throws(()=>planPolicySplit(offList,inputSpec,now),e=>/POLICY_SPLIT_UNPARSED/.test(e.message)&&/드롭다운 목록 밖/.test(e.holds[0]));
  const bad=splitFixture({'대인/면책':'무한'});assert.throws(()=>planPolicySplit(bad,inputSpec,now),e=>/POLICY_SPLIT_UNPARSED/.test(e.message)&&e.holds.length===1);
  const formula=splitFixture();formula.spreadsheet.sheets[2].data[0].rowData[1].values[old.indexOf('승계')]={userEnteredValue:{formulaValue:'=A1'}};assert.throws(()=>planPolicySplit(formula,inputSpec,now),/POLICY_SPLIT_UNPARSED/);
  const short=splitFixture();short.spreadsheet.sheets[2].properties.gridProperties.rowCount=10;assert.throws(()=>planPolicySplit(short,inputSpec,now),/full-height/);
  assert.throws(()=>planPolicySplit(fixture(),inputSpec,now),/LAYOUT_MISMATCH/,'already split or other layout holds');});
const reorderFixture=()=>{const f=fixture();f.spreadsheet.sheets=f.spreadsheet.sheets.map(sh=>{const id=sh.properties.sheetId;if(id===2)return sh;const t=sheet(id,sh.properties.title,splitH);t.properties.gridProperties={...t.properties.gridProperties,columnCount:71};return t;});return f;};
test('layout reorder: appends new columns, moves whole columns into the 대표 order, renames headers, never rewrites cell values',()=>{
  const f=reorderFixture(),before=JSON.stringify(f),p=planLayoutReorder(f,inputSpec,now);assert.equal(JSON.stringify(f),before);assert.equal(p.to,'2026-10-03-order');
  assert.ok(p.requests.every(r=>['insertDimension','moveDimension','updateCells','updateDimensionProperties','setDataValidation'].includes(Object.keys(r)[0])));
  const mine=p.requests.filter(r=>JSON.stringify(r).includes('"sheetId":3,')||JSON.stringify(r).includes('"sheetId":3}'));
  // Simulate the moves on the old header order and check the result is the new layout.
  const sim=[...splitH,...inputSpec.layoutReorder.newColumns.map(h=>'NEW:'+h)];
  for(const r of mine){if(r.moveDimension){const {startIndex}=r.moveDimension.source;sim.splice(r.moveDimension.destinationIndex,0,sim.splice(startIndex,1)[0]);}}
  const renamed=sim.map(h=>h.startsWith('NEW:')?h.slice(4):({'세부모델':'모델','옵션':'옵션 원문'}[h]??h));assert.deepEqual(renamed,inputSpec.inputHeaders);
  const cellWrites=p.requests.filter(r=>r.updateCells&&r.updateCells.start.rowIndex!==0&&r.updateCells.start.sheetId!==1);assert.equal(cellWrites.length,0,'no data cell rewritten');
  const head=p.requests.find(r=>r.updateCells&&r.updateCells.start.sheetId===3).updateCells.rows[0].values.map(v=>v.userEnteredValue.stringValue);assert.deepEqual(head,inputSpec.inputHeaders);
  const sum=p.requests.filter(r=>r.updateCells?.start.sheetId===1)[0].updateCells;assert.equal(sum.rows[0].values.length,74);assert.match(sum.rows[1].values[0].userEnteredValue.formulaValue,/'웰릭스'!A2:BV1000/);
  assert.equal(p.requests.filter(r=>r.setDataValidation&&r.setDataValidation.range.sheetId===3).length,3);
  assert.throws(()=>planLayoutReorder(fixture(),inputSpec,now),/LAYOUT_MISMATCH/,'only from the split layout');});
