import test from 'node:test';
import assert from 'node:assert/strict';
import {planSupplierInput,planPolicyImport,buildPolicyArchive,inputSpec} from '../scripts/supplier-input-sheet.mjs';
const now=Date.parse('2026-10-03T12:00:00Z');
const legacy=inputSpec.legacyLayouts['2026-10-02'];
const sheet=(id,title,headers,grid={frozenRowCount:1,frozenColumnCount:0})=>({properties:{sheetId:id,title,gridProperties:{rowCount:1000,columnCount:headers.length,...grid}},data:[{rowData:[{values:headers.map(h=>({userEnteredValue:{stringValue:h}}))}]}]});
const fixture=()=>({capturedAt:new Date(now).toISOString(),binding:{spreadsheetId:'test',summarySheetId:1,guideSheetId:2,suppliers:[{sheetId:3,title:'예시',code:'TEST'}]},sheetInventory:[1,2,3].map(sheetId=>({sheetId})),spreadsheet:{spreadsheetId:'test',sheets:[sheet(1,'종합',inputSpec.summaryHeaders),sheet(2,'관리안내',['안내']),sheet(3,'예시',inputSpec.inputHeaders)]}});
const policyFixture=()=>{const f=fixture(),d=sheet(3,'예시',legacy.inputHeaders);const h=legacy.inputHeaders,values=h.map(()=>({}));values[h.indexOf('차량번호')]={userEnteredValue:{stringValue:'TEST-1'}};values[h.indexOf('정책코드')]={userEnteredValue:{stringValue:'POL-01'}};d.data[0].rowData.push({values});return {runId:'test-run',capturedAt:f.capturedAt,suppliers:[{sheetId:3,sourceId:'source',sourceTab:'policy'}],destinations:[d],captures:[{sourceId:'source',sourceTab:'policy',complete:true,rows:[{values:['정책코드','추가주행 금액','정비'].map(stringValue=>({userEnteredValue:{stringValue}}))},{values:['POL-01','대여료의 10%','연2회오일'].map(stringValue=>({userEnteredValue:{stringValue}}))}]}]};};

test('2026-10-03 layout: 30 vehicle/rate columns then 32 policy columns, no refinement or policy-code columns',()=>{
  assert.equal(inputSpec.layoutVersion,'2026-10-03');
  assert.equal(inputSpec.vehicleHeaders.length,30);assert.equal(inputSpec.policyHeaders.length,32);
  assert.deepEqual(inputSpec.inputHeaders,[...inputSpec.vehicleHeaders,...inputSpec.policyHeaders]);
  assert.deepEqual(inputSpec.summaryHeaders,inputSpec.inputHeaders);
  assert.equal(new Set(inputSpec.inputHeaders).size,62);
  assert.deepEqual(inputSpec.inputHeaders.slice(0,7),['회사명','차량상태','상품구분','차량번호','제조사','세부모델','차명 원문']);
  assert.equal(inputSpec.vehicleHeaders.at(-1),'차량가격');
  assert.deepEqual(inputSpec.policyHeaders.slice(0,8),['예외사항','심사','보험료','기본연령','면허기간','연주행','1만km+','21세+']);
  assert.equal(inputSpec.policyHeaders.at(-1),'비고');assert.ok(inputSpec.policyHeaders.includes('계좌번호'));
  for(const gone of ['정책코드','점검사항','차종코드','차명(정제)','제조사(정제)','26세+'])assert.ok(!inputSpec.inputHeaders.includes(gone),gone);
  assert.equal(inputSpec.frozenRowCount,1);assert.equal(inputSpec.frozenColumnCount,0);assert.equal(inputSpec.font.italic,false);
  assert.ok(!inputSpec.numberHeaders.includes('연식'));
});
test('matching sheet verifies with zero write requests and leaves input untouched',()=>{const f=fixture(),before=JSON.stringify(f),r=planSupplierInput(f,inputSpec,now);assert.equal(JSON.stringify(f),before);assert.equal(r.status,'LAYOUT_VERIFIED');assert.deepEqual(r.requests,[]);assert.match(r.scope,/VERIFY_ONLY/);});
test('any header difference is LAYOUT_MISMATCH HOLD — old 2026-10-02 layout, reorder, missing, extra',()=>{
  const cases=[f=>{f.spreadsheet.sheets[2]=sheet(3,'예시',legacy.inputHeaders);},f=>{f.spreadsheet.sheets[0]=sheet(1,'종합',legacy.summaryHeaders);},f=>{f.spreadsheet.sheets[2].data[0].rowData[0].values.reverse();},f=>{f.spreadsheet.sheets[2].data[0].rowData[0].values.pop();},f=>{f.spreadsheet.sheets[2].data[0].rowData[0].values.push({userEnteredValue:{stringValue:'정책코드'}});},f=>{f.spreadsheet.sheets[2].data[0].rowData[0].values[0].userEnteredValue.stringValue='';}];
  for(const mutate of cases){const f=fixture();mutate(f);assert.throws(()=>planSupplierInput(f,inputSpec,now),e=>/HOLD: LAYOUT_MISMATCH/.test(e.message)&&e.mismatched.length===1);}
});
test('extra trailing header cells and hidden bound tabs are HOLD; hidden unbound archive tabs are ignored',()=>{const a=fixture();a.spreadsheet.sheets[2].data[0].rowData[0].values.push({});assert.throws(()=>planSupplierInput(a,inputSpec,now),/LAYOUT_MISMATCH/);for(const id of [0,2]){const f=fixture();f.spreadsheet.sheets[id].properties.hidden=true;assert.throws(()=>planSupplierInput(f,inputSpec,now),e=>/LAYOUT_MISMATCH/.test(e.message)&&e.mismatched[0].hidden===true);}const f=fixture();f.spreadsheet.sheets.push({...sheet(9,'정책원문',['runId']),properties:{sheetId:9,title:'정책원문',hidden:true,gridProperties:{rowCount:10,columnCount:1}}});f.sheetInventory.push({sheetId:9});assert.equal(planSupplierInput(f,inputSpec,now).status,'LAYOUT_VERIFIED');});
test('frozen rows/columns drift is reported, never written',()=>{const f=fixture();f.spreadsheet.sheets[2].properties.gridProperties.frozenColumnCount=2;const r=planSupplierInput(f,inputSpec,now);assert.equal(r.status,'LAYOUT_VERIFIED_WITH_PRESENTATION_DRIFT');assert.deepEqual(r.drift.map(d=>[d.sheetId,d.frozenColumnCount]),[[3,2]]);assert.deepEqual(r.requests,[]);});
test('fail closed binding freshness inventory duplicate and production workbook',()=>{for(const mutate of [f=>f.binding.spreadsheetId='other',f=>f.capturedAt='2026-09-01',f=>f.sheetInventory.pop(),f=>f.binding.suppliers.push({...f.binding.suppliers[0]}),f=>{f.spreadsheet.sheets.push(sheet(4,'숨김아님',['x']));f.sheetInventory.push({sheetId:4});}]){const f=fixture();mutate(f);assert.throws(()=>planSupplierInput(f,inputSpec,now),/HOLD/);}});
test('planner refuses a spec that is not verify-only',()=>{assert.throws(()=>planSupplierInput(fixture(),{...inputSpec,plannerMode:'WRITE'},now),/VERIFY_ONLY/);});
test('manual authority is explicit and automatic source refresh stays disabled',()=>{assert.equal(inputSpec.managementMode,'MANUAL_DIRECT_GOOGLE_SHEETS');assert.equal(inputSpec.manualAuthority,'VISIBLE_SUPPLIER_TABS');assert.equal(inputSpec.automaticSourceRefresh,false);});
test('policy import refuses the current layout because it has no 정책코드',()=>{const f=policyFixture();f.destinations=[sheet(3,'예시',inputSpec.inputHeaders)];assert.throws(()=>planPolicyImport(f,now),/2026-10-02 layout only/);});
test('compact policy retains money units, zero, one-sided bounds and repair percent basis',()=>{for(const [low,high,expected]of [['50만원','100만원','50~100만원'],['50만원','50만원','50만원'],['50만원','','최소 50만원'],['','100만원','최대 100만원'],['50만원','1억원','50만원~1억원'],[0,0,'0']]){const f=policyFixture(),src=f.captures[0].rows;const names=['대인보상한도','대인면책금','자차보상한도','자차수리비율','자차최소면책금','자차최대면책금'];src[0].values.push(...names.map(stringValue=>({userEnteredValue:{stringValue}})));src[1].values.push(...['무한',0,'차량가액','20%',low,high].map(v=>({userEnteredValue:typeof v==='number'?{numberValue:v}:{stringValue:v}})));const p=planPolicyImport(f,now);assert.equal(p.writes.find(w=>w.header==='대인').value.stringValue,'무한 / 0');const car=p.writes.find(w=>w.header==='자차');assert.equal(car.value.stringValue,'차량가액 / 수리비 20% / '+expected);assert.match(car.fullDescription,/자차수리비율: 20%/);}});
test('compact rewrite requires exact import ownership and old presentation; repeat is idempotent',()=>{for(const variant of ['owned','edited','unowned']){const f=policyFixture(),src=f.captures[0].rows;src[0].values.push(...['대인보상한도','대인면책금'].map(stringValue=>({userEnteredValue:{stringValue}})));src[1].values.push(...['무한','50만원'].map(stringValue=>({userEnteredValue:{stringValue}})));const ci=legacy.inputHeaders.indexOf('대인'),cells=f.destinations[0].data[0].rowData[1].values;cells[ci]={userEnteredValue:{stringValue:'대인보상한도: 무한\n대인면책금: '+(variant==='edited'?'60만원':'50만원')},note:'원문 정책 이관 / '+(variant==='unowned'?'other':'original')+' / policy 2행 / POL-01 / 원천 단위 그대로'};f.rewriteImportedPolicyPresentation={runId:'original'};const p=planPolicyImport(f,now),w=p.writes.find(w=>w.header==='대인');if(variant==='owned'){assert.equal(w.value.stringValue,'무한 / 50만원');assert.ok(w.previous.note.includes('original'));for(const write of p.writes)cells[write.column]={userEnteredValue:write.value,note:write.previous?.note??'import'};assert.equal(planPolicyImport(f,now).writes.length,0);}else{assert.equal(w,undefined);assert.ok(p.holds.some(h=>h.reason==='POLICY_PRESENTATION_NOT_OWNED_OR_CHANGED'));}}});
test('policy exact binding, zero/formula preservation and original rate text',()=>{const f=policyFixture(),col=legacy.inputHeaders.indexOf('정비');f.destinations[0].data[0].rowData[1].values[col]={userEnteredValue:{formulaValue:'=""'},effectiveValue:{stringValue:''}};const p=planPolicyImport(f,now);assert.equal(p.writes.length,1);assert.equal(p.writes[0].value.stringValue,'대여료의 10%');assert.equal(p.writes[0].source.runId,'test-run');assert.equal(p.outcomes[0].status,'MATCHED');});
test('unreadable source fails; blank/ambiguous/numeric codes hold without generic fallback',()=>{const broken=policyFixture();broken.captures[0].complete=false;assert.throws(()=>planPolicyImport(broken,now),/HOLD/);for(const kind of ['blank','duplicate','numeric']){const f=policyFixture();if(kind==='duplicate')f.captures[0].rows.push(f.captures[0].rows[1]);else f.destinations[0].data[0].rowData[1].values[legacy.inputHeaders.indexOf('정책코드')]={userEnteredValue:kind==='numeric'?{numberValue:12}:{stringValue:''}};const p=planPolicyImport(f,now);assert.equal(p.writes.length,0);assert.equal(p.holds.length,1);assert.equal(p.outcomes.length,1);}});
test('archive aligns by label when source schemas differ; records schema hash and raw formula',()=>{const f=policyFixture(),other={sourceId:'second',sourceTab:'policy',complete:true,rows:[{values:['정비','정책코드'].map(stringValue=>({userEnteredValue:{stringValue}}))},{values:[{userEnteredValue:{formulaValue:'="미제공"'},effectiveValue:{stringValue:'미제공'}},{userEnteredValue:{stringValue:'POL-02'}}]}]};const a=buildPolicyArchive([...f.captures,other],'run',f.capturedAt);assert.equal(a.rows[2].values[a.headers.indexOf('정책코드')].userEnteredValue.stringValue,'POL-02');assert.equal(a.rows[2].values[a.headers.indexOf('정비')].note,'원천 수식: ="미제공"');assert.notEqual(a.rows[1].values[5].userEnteredValue.stringValue,a.rows[2].values[5].userEnteredValue.stringValue);});
test('source 0.2 displays 20 percent without changing raw numeric value or losing unit note',()=>{const f=policyFixture();f.captures[0].rows[0].values.push({userEnteredValue:{stringValue:'자차수리비율'}});f.captures[0].rows[1].values.push({userEnteredValue:{numberValue:0.2},effectiveValue:{numberValue:0.2},formattedValue:'20%',userEnteredFormat:{numberFormat:{type:'PERCENT',pattern:'0%'}},note:'수리비의 비율'});const p=planPolicyImport(f,now);assert.equal(p.writes.find(w=>w.header==='자차').value.stringValue,'수리비 20%');const a=buildPolicyArchive(f.captures,'run',f.capturedAt),c=a.rows[1].values[a.headers.indexOf('자차수리비율')];assert.equal(c.userEnteredValue.numberValue,0.2);assert.equal(c.userEnteredFormat.numberFormat.type,'PERCENT');assert.equal(c.note,'수리비의 비율');});
